### ISSUE TITLE
Polygon query...  possible?

### ISSUE THREAD

**Issue by fils** [akhenakh/regionagogo#2]
I found your library while researching approaches for searching scientific drilling data for US research community.

It's very close already to the need I have.  All my data in simple points (which I can put into a geojson format).    However, I need to search using arbitrary polygon shapes.   I see you have a circle and a rectangle search already. 

If you could give me some guidance I would love to take a stab at making a polygon search..  though I only learned about s2 recently and know little about it so far.  

If I load this system with data in geojson that is POINT not POLYGON will that still work?

I assume a polygon search will be like your rectangle search?  I just need to make the s2 instance of the polygon?   

Thanks much..

**Comment by akhenakh** [comment]
What you want is the opposite of regionagogo, storing points and querying for a shape right ?

**Comment by fils** [comment]
@akhenakh correct..  I have lots of points (drill sites) and the searchers tend to be polygons (some circle radius stuff too)

**Comment by akhenakh** [comment]
You should give a look to my blog post about exactly what you need: http://blog.nobugware.com/post/2016/geo_db_s2_geohash_database/

You better start from this rather than using regionagogo which is really dedicated to the opposite query storing polygons and querying stubbing queries.

There are some code on the blogpost to achieve that but it's not as complete as a regionagogo. Depends of your skills in Go.
I have it working but not ready for opensource publishing :/, but it's actually quite simple.

Hope it was helpful.

**Comment by akhenakh** [comment]
Nothing also forbids to modify regionagogo to accept polygons as query ...
And query for really small cell (level 30) to make it looks like a point
